// This file is autogenerated by VESC Tool

#ifndef ORTHOPUS_CONFXML_H_
#define ORTHOPUS_CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_ORTHOPUS_CONFIG_T__SIZE		2578

// Variables
extern uint8_t data_orthopus_config_t_[];

// ORTHOPUS_CONFXML_H_
#endif
