// This file is autogenerated by VESC Tool

#ifndef ORTHOPUS_CONFPARSER_H_
#define ORTHOPUS_CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define ORTHOPUS_CONFIG_T_SIGNATURE		2447436864

// Functions
int32_t orthopus_confparser_serialize_orthopus_config_t(uint8_t *buffer, const orthopus_config_t *conf);
bool orthopus_confparser_deserialize_orthopus_config_t(const uint8_t *buffer, orthopus_config_t *conf);
void orthopus_confparser_set_defaults_orthopus_config_t(orthopus_config_t *conf);

// ORTHOPUS_CONFPARSER_H_
#endif
