// This file is autogenerated by VESC Tool

#include <string.h>
#include "buffer.h"
#include "conf_general.h"
#include "orthopus_confparser.h"

int32_t orthopus_confparser_serialize_orthopus_config_t(uint8_t *buffer, const orthopus_config_t *conf) {
	int32_t ind = 0;

	buffer_append_uint32(buffer, ORTHOPUS_CONFIG_T_SIGNATURE, &ind);

	strcpy((char*)buffer + ind, conf->joint_name);
	ind += strlen(conf->joint_name) + 1;
	buffer[ind++] = conf->simu_mode;
	buffer[ind++] = (uint8_t)conf->stream_rate_10;
	buffer_append_float32_auto(buffer, conf->encoder_offset, &ind);
	buffer_append_float32_auto(buffer, conf->encoder_max_diff, &ind);
	buffer[ind++] = conf->limits_enable;
	buffer[ind++] = conf->limits_enable_reaction;
	buffer_append_float32_auto(buffer, conf->limits_pos_min, &ind);
	buffer_append_float32_auto(buffer, conf->limits_pos_max, &ind);
	buffer_append_float32_auto(buffer, conf->limits_kp, &ind);
	buffer_append_float32_auto(buffer, conf->limits_kd, &ind);
	buffer_append_int32(buffer, conf->limits_powp, &ind);
	buffer_append_int32(buffer, conf->limits_powd, &ind);
	buffer_append_int32(buffer, conf->limits_damp_reachangle, &ind);
	buffer_append_float32_auto(buffer, conf->limits_reach_angle, &ind);
	buffer_append_float32_auto(buffer, conf->limits_reach_speed, &ind);
	buffer_append_int32(buffer, conf->perf_rate_hz, &ind);
	buffer[ind++] = conf->perf_compensateexectime;
	buffer[ind++] = conf->ctrl_deadzone;
	buffer[ind++] = conf->ctrl_sample_adc3;
	buffer_append_float32_auto(buffer, conf->ctrl_stiffness, &ind);
	buffer_append_float32_auto(buffer, conf->ctrl_torquezero, &ind);
	buffer_append_float32_auto(buffer, conf->ctrl_torquegain, &ind);
	buffer_append_float32_auto(buffer, conf->ctrl_damping, &ind);
	buffer_append_float32_auto(buffer, conf->ctrl_kp, &ind);
	buffer_append_float32_auto(buffer, conf->ctrl_a, &ind);
	buffer_append_float32_auto(buffer, conf->ctrl_kd, &ind);
	buffer_append_float32_auto(buffer, conf->ctrl_kd_filter, &ind);
	buffer_append_float32_auto(buffer, conf->torque_filter_const, &ind);
	buffer_append_float32_auto(buffer, conf->safety_max_q_error, &ind);
	buffer_append_float32_auto(buffer, conf->safety_max_speed, &ind);
	buffer[ind++] = conf->auto_clear_errors;
	buffer[ind++] = conf->safety_track_disable;
	buffer[ind++] = conf->safety_timeout_disable;
	buffer[ind++] = conf->safety_max_speed_disable;
	buffer_append_float32_auto(buffer, conf->ff_torque_constant, &ind);

	return ind;
}

bool orthopus_confparser_deserialize_orthopus_config_t(const uint8_t *buffer, orthopus_config_t *conf) {
	int32_t ind = 0;

	uint32_t signature = buffer_get_uint32(buffer, &ind);
	if (signature != ORTHOPUS_CONFIG_T_SIGNATURE) {
		return false;
	}

	strcpy(conf->joint_name, (char*)buffer + ind);
	ind += strlen(conf->joint_name) + 1;
	conf->simu_mode = buffer[ind++];
	conf->stream_rate_10 = buffer[ind++];
	conf->encoder_offset = buffer_get_float32_auto(buffer, &ind);
	conf->encoder_max_diff = buffer_get_float32_auto(buffer, &ind);
	conf->limits_enable = buffer[ind++];
	conf->limits_enable_reaction = buffer[ind++];
	conf->limits_pos_min = buffer_get_float32_auto(buffer, &ind);
	conf->limits_pos_max = buffer_get_float32_auto(buffer, &ind);
	conf->limits_kp = buffer_get_float32_auto(buffer, &ind);
	conf->limits_kd = buffer_get_float32_auto(buffer, &ind);
	conf->limits_powp = buffer_get_int32(buffer, &ind);
	conf->limits_powd = buffer_get_int32(buffer, &ind);
	conf->limits_damp_reachangle = buffer_get_int32(buffer, &ind);
	conf->limits_reach_angle = buffer_get_float32_auto(buffer, &ind);
	conf->limits_reach_speed = buffer_get_float32_auto(buffer, &ind);
	conf->perf_rate_hz = buffer_get_int32(buffer, &ind);
	conf->perf_compensateexectime = buffer[ind++];
	conf->ctrl_deadzone = buffer[ind++];
	conf->ctrl_sample_adc3 = buffer[ind++];
	conf->ctrl_stiffness = buffer_get_float32_auto(buffer, &ind);
	conf->ctrl_torquezero = buffer_get_float32_auto(buffer, &ind);
	conf->ctrl_torquegain = buffer_get_float32_auto(buffer, &ind);
	conf->ctrl_damping = buffer_get_float32_auto(buffer, &ind);
	conf->ctrl_kp = buffer_get_float32_auto(buffer, &ind);
	conf->ctrl_a = buffer_get_float32_auto(buffer, &ind);
	conf->ctrl_kd = buffer_get_float32_auto(buffer, &ind);
	conf->ctrl_kd_filter = buffer_get_float32_auto(buffer, &ind);
	conf->torque_filter_const = buffer_get_float32_auto(buffer, &ind);
	conf->safety_max_q_error = buffer_get_float32_auto(buffer, &ind);
	conf->safety_max_speed = buffer_get_float32_auto(buffer, &ind);
	conf->auto_clear_errors = buffer[ind++];
	conf->safety_track_disable = buffer[ind++];
	conf->safety_timeout_disable = buffer[ind++];
	conf->safety_max_speed_disable = buffer[ind++];
	conf->ff_torque_constant = buffer_get_float32_auto(buffer, &ind);

	return true;
}

void orthopus_confparser_set_defaults_orthopus_config_t(orthopus_config_t *conf) {
	strcpy(conf->joint_name, ORTHOPUS_CFG_DEF_JOINT_NAME);
	conf->simu_mode = ORTHOPUS_CFG_DEF_SIMU_MODE;
	conf->stream_rate_10 = ORTHOPUS_CFG_DEF_STREAM_RATE_10;
	conf->encoder_offset = ORTHOPUS_CFG_DEF_ENCODER_OFFSET;
	conf->encoder_max_diff = ORTHOPUS_CFG_DEF_ENCODER_MAX_DIFF;
	conf->limits_enable = ORTHOPUS_CFG_DEF_LIMITS_ENABLE;
	conf->limits_enable_reaction = ORTHOPUS_CFG_DEF_LIMITS_ENABLE_REACTION;
	conf->limits_pos_min = ORTHOPUS_CFG_DEF_LIMITS_POS_MIN;
	conf->limits_pos_max = ORTHOPUS_CFG_DEF_LIMITS_POS_MAX;
	conf->limits_kp = ORTHOPUS_CFG_DEF_LIMITS_KP;
	conf->limits_kd = ORTHOPUS_CFG_DEF_LIMITS_KD;
	conf->limits_powp = ORTHOPUS_CFG_DEF_LIMITS_POWP;
	conf->limits_powd = ORTHOPUS_CFG_DEF_LIMITS_POWD;
	conf->limits_damp_reachangle = ORTHOPUS_CFG_DEF_LIMITS_DAMP_REACHANGLE;
	conf->limits_reach_angle = ORTHOPUS_CFG_DEF_LIMITS_REACH_ANGLE;
	conf->limits_reach_speed = ORTHOPUS_CFG_DEF_LIMITS_REACH_SPEED;
	conf->perf_rate_hz = ORTHOPUS_CFG_DEF_PERF_RATE_HZ;
	conf->perf_compensateexectime = ORTHOPUS_CFG_DEF_PERF_COMPENSATEEXECTIME;
	conf->ctrl_deadzone = ORTHOPUS_CFG_DEF_CTRL_DEADZONE;
	conf->ctrl_sample_adc3 = ORTHOPUS_CFG_DEF_CTRL_SAMPLE_ADC3;
	conf->ctrl_stiffness = ORTHOPUS_CFG_DEF_CTRL_STIFFNESS;
	conf->ctrl_torquezero = ORTHOPUS_CFG_DEF_CTRL_TORQUEZERO;
	conf->ctrl_torquegain = ORTHOPUS_CFG_DEF_CTRL_TORQUEGAIN;
	conf->ctrl_damping = ORTHOPUS_CFG_DEF_CTRL_DAMPING;
	conf->ctrl_kp = ORTHOPUS_CFG_DEF_CTRL_KP;
	conf->ctrl_a = ORTHOPUS_CFG_DEF_CTRL_A;
	conf->ctrl_kd = ORTHOPUS_CFG_DEF_CTRL_KD;
	conf->ctrl_kd_filter = ORTHOPUS_CFG_DEF_CTRL_KD_FILTER;
	conf->torque_filter_const = ORTHOPUS_CFG_DEF_TORQUE_FILTER_CONST;
	conf->safety_max_q_error = ORTHOPUS_CFG_SAFETY_MAX_Q_ERROR;
	conf->safety_max_speed = ORTHOPUS_CFG_DEF_SAFETY_MAX_SPEED;
	conf->auto_clear_errors = ORTHOPUS_CFG_DEF_AUTO_CLEAR_ERRORS;
	conf->safety_track_disable = ORTHOPUS_CFG_DEF_SAFETY_TRACK_DISABLE;
	conf->safety_timeout_disable = ORTHOPUS_CFG_DEF_SAFETY_TIMEOUT_DISABLE;
	conf->safety_max_speed_disable = ORTHOPUS_CFG_DEF_DISABLE_SAFETY_MAX_SPEED;
	conf->ff_torque_constant = ORTHOPUS_CFG_DEF_FF_TORQUE_CONSTANT;
}

